services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
    ports:
      - "82:80"
      - "83:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
