version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "8787:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/nama_user_hosting/web:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./php
    container_name: php
    volumes:
      - /var/www/nama_user_hosting/web:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ahmadrafi01
      MYSQL_DATABASE: terarush
      MYSQL_USER: terarush
      MYSQL_PASSWORD: ahmadrafi01
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8789:80"
    depends_on:
      - mysql
    networks:
      - app-network

  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    ports:
      - "8791:8080"
    volumes:
      - /var/www/nama_user_hosting/web:/data
      - ./filebrowser.db:/config
    environment:
      - FB_BASEURL=/filebrowser
    networks:
      - app-network
    restart: unless-stopped

volumes:
  db-data:


networks:
  app-network:
    driver: bridge

