services:
  runner:
    container_name: gitea_runner_1
    image: docker.io/gitea/act_runner:nightly
    environment:
      GITEA_INSTANCE_URL: "http://gitea:3000"
      GITEA_RUNNER_REGISTRATION_TOKEN: "TrMwj24AQSqZQ7gUzl0yOJ7mjPQ2Op7zIMkA6c8x"
      GITEA_RUNNER_NAME: "Gitea Runner #1"
    networks:
      - root_gitea
    volumes:
      - ./config.yaml:/config.yaml
      - /var/lib/gitea/runner/1/:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  root_gitea:
    external: true

    # add same network with gitea networks
